/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef PERIPHERALS_H
#define PERIPHERALS_H

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_i2c.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* BOARD_InitPeripherals defines for FLEXCOMM4 */
/* Definition of peripheral ID */
#define FLEXCOMM4_PERIPHERAL ((I2C_Type *)FLEXCOMM4)
/* Definition of the clock source frequency */
#define FLEXCOMM4_CLOCK_SOURCE 12000000UL
/* FLEXCOMM4 interrupt vector ID (number). */
#define FLEXCOMM4_FLEXCOMM_IRQN FLEXCOMM4_IRQn
/* Transfer buffer size. */
#define FLEXCOMM4_BUFFER_SIZE 10

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const i2c_master_config_t FLEXCOMM4_config;
extern i2c_master_handle_t FLEXCOMM4_handle;
extern uint8_t FLEXCOMM4_buffer[FLEXCOMM4_BUFFER_SIZE];
extern i2c_master_transfer_t FLEXCOMM4_transfer;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* PERIPHERALS_H */
